# Introduction

## What is Native Cover?

The conservation and restoration of biodiversity is a global priority @UN2020, with the recent adoption of targets and goals through the 2022 Kunming-Montreal Global Biodiversity Framework (GBF) representing a global commitment to reverse the decline in biodiversity. Habitat loss is considered to be the primary cause of the global decline in biodiversity in recent decades [@Millennium2005; @Newbold2015; @SemperPascual2021]. The availability of high-quality habitat has been linked to species richness, species resilience and biodiversity [@Rosenzweig1995; @Klok1998; @Wilson2002; @Ribic2009; @Ramesh2016]. Conversely, replacing native habitat (‘native cover’) with anthropogenic land uses (‘human footprints’) has been shown to reduce biodiversity [@Vitousek1997; @Crooks1999; @Laurance2001; @Sanderson2002].

A key aspect of the GBF is tracking progress of the targets and goals through the development and monitoring of indicators. Alberta Environment and Protected Areas, in partnership with the Alberta Biodiversity Monitoring Institute (ABMI), developed the Native Cover indicator to support biodiversity conservation and land-use management. ‘Native cover’ is defined as an area that is free of visible anthropogenic alteration (human footprint). ‘Human footprint’ is any area visibly altered for anthropogenic land use. The Native Cover indicator quantifies one facet of biodiversity loss by tracking the amount of native cover converted to human footprints, typically for settlement, agriculture, resource extraction, and transportation.

## How can it be measured?

This indicator measures two types of native cover:

- **Aquatic native cover** represents the amount of aquatic habitat including bogs, fens, swamps, marshes, open water, and riparian areas.

- **Terrestrial native cover** represents the amount of habitat not identified as aquatic habitat (i.e., upland).

For each indicator, we delineated the areas of aquatic and terrestrial native cover and then overlaid human footprint to assess the **current** condition, while discounting for harvest area recovery. The **reference** condition was assessed as the total area of aquatic and terrestrial native cover without the presence of human footprint. This indicator is then presented as the percentage of current native cover (i.e., with footprint) relative to the reference state (i.e., without footprint).